// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wjxhejawdavqohymsuxi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndqeGhlamF3ZGF2cW9oeW1zdXhpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ4MjY3NTMsImV4cCI6MjA2MDQwMjc1M30.zuSJ6WcUBZcGjATd3qU6BGYNan52gCqSvbFJEsDclK8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);